### ISSUE TITLE
App shows incorrect instructions to enter DFU mode for iPhone 7, 8 and X users(and plus variants)

### ISSUE THREAD

**Issue by Swastik496** [checkra1n/BugTracker#151]
**What device + iOS version are you on?**
iPhone 8 Plus iOS 13.3b1. This issue applies for all devices without a physical home button pre iPhone XS. 
**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Open Mac App and enter recovery mode(or enter it manually if on 13.3b1)
2. Try to follow instructions to enter DFU Mode 
3. The device will restart instead
...
**What do you expect, and what is happening instead?**
I expect the app to have me follow these instructions instead if I am on an iPhone 8/Plus/X or iPhone 7 because the regular ones are incorrect. 
https://www.reddit.com/r/jailbreak/comments/duceo2/tip_for_checkra1n_dfu_mode/
**Any other info, error logs, screenshots, ...?**
I know there is already a bug report on this from someone else but that one doesn't show the correct instructions on how to actually do this and so I put up this one because I think it might make it easier to fix for you.

**Comment by Lonegwadiwaitor** [comment]
I think Checkra1n displays those instructions based on what device is plugged in at the time, weird how it's showing 6s and before diagram for 7 and above.

I just tested it myself on my 7 Plus and it seems to be working normally.

**Comment by gurkentier** [comment]
I have to confirm: DFU instructions are not working on iPhone 8.
Note: I used v0.9 so I don’t know if it’s fixed in 0.9.1

**Comment by IanLulz** [comment]
Still wrong in 0.9.2. iPX, USB-A cable is required to enter DFU for some reason (USB-C cable will not work. I swear. Must be some Apple black magic.), but with a USB-A the instructions are almost there, you just need to hold down VOLUME DOWN+POWER (side button) immediately after the screen shuts off. The checkra1n GUI has a pause in-between these actions.

**Comment by dunklesToast** [comment]
> USB-A cable is required to enter DFU

This! I tried it for the last 30min with a USB C Cable and it did not work. This info should be written in the "Enter DFU Mode" Screen in checkrain

**Comment by littlelailo** [comment]
Duplicate of #12
