### ISSUE TITLE
A10 not working iOS 14.3 even with Allow Untrusted versions (error -79)

### ISSUE THREAD

**Issue by mheealx** [checkra1n/BugTracker#1879]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? iOS 14.3 Beta 3
3. What version of checkra1n are you using? 0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux, ElementaryOS 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A original cable and 3rd party cable, connected directly 

**What are the steps to reproduce the issue?**
1. Open checkra1n in terminal
2. Connect the iPhone with iOS 14.3 (not matters if beta 1, 2 or even 3) 
3. Tick the Allow untrusted versions of iOS and even Safemode.
4. run checkra1n
5. It’ll give you an error -79
...

**What do you expect, and what is happening instead?**
I expect my iPhone turn on into a jailbroken mode but instead of that it turns on normally with no jailbreak and the checkra1n says, USBMUXD ERROR -79

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Yep, known issue. It's in the patch notes.

**Comment by harmonium76** [comment]
Hi luiszaarate! Did you've found any solutions? I think i have the same situation here. Did you try restoring a backup or just connect your phone using a USB cable to see if iTunes can see your phone?

**Comment by Siguza** [comment]
There is no solution. We need to write a new iBoot patch.

**Comment by harmonium76** [comment]
Hi Siguza! Can you take a minute to explain what is : iBoot patch?

**Comment by MarHansen** [comment]
I got the same issue on the same device

**Comment by harmonium76** [comment]
Hi BuayaaDarat!, i'm stocked there, i can not use iTunes for restore, reinstall or update, iTunes doesn't recognize my iPhone, iMazing do recognize my phone but i can not restore a backup or reinstall IOS??? I think Siguza was right about: There is no solution. We need to write a new iBoot patch. But i don't want to go there, i'm not a pro dealing with going too deep in the system. Since that situation started, my phone is still working but... If you find something, i'll appreciate if you can let me know, i'll do the same, i'll let you know! May be a new major update from Apple or a new version of checkra1n will help! Thanks! Merry Christmas to all!

**Comment by MarHansen** [comment]
> Hi BuayaaDarat!, i'm stocked there, i can not use iTunes for restore, reinstall or update, iTunes doesn't recognize my iPhone, iMazing do recognize my phone but i can not restore a backup or reinstall IOS??? I think Siguza was right about: There is no solution. We need to write a new iBoot patch. But i don't want to go there, i'm not a pro dealing with going too deep in the system. Since that situation started, my phone is still working but... If you find something, i'll appreciate if you can let me know, i'll do the same, i'll let you know! May be a new major update from Apple or a new version of checkra1n will help! Thanks! Merry Christmas to all!

Since the checkra1n version is still on beta and they already mentioned it on “known issue” section about A10/A10x issues,maybe i’ll wait until the final release came out or maybe 0.12.2 beta version.

**Comment by liu-congcong** [comment]
I got the same issue on iPad2018 :(

**Comment by Siguza** [comment]
Fixed in 0.12.2.

**Comment by harmonium76** [comment]
Yes! Fixed in 0.12.2. Yes i can now jailbreak my phone. But the problem is still there, i can not see my iPhone with iTunes and with iMazing, same thing, i see it but can not restore backup or reinstall IOS, soooo, i used checra1n to remove the jailbreak, it works but after that, its still the same situation, can not see it with iTunes and same with iMazing. What can i do?

**Comment by harmonium76** [comment]
Hi Siguza! If you have time, i will thank you, did you found something new about that situation: <We need to write a new iBoot patch> I'm still unable to restore a backup or at least reinstall IOS
ref.: #1879

**Comment by Siguza** [comment]
Just put it in recovery mode. If you still can't restore it, then that's Apple's fault. You can always use idevicerestore though...

**Comment by harmonium76** [comment]
Thank you so much, the sun is shinning again! i have used Reiboot to make a clean install and it worked. Houra!!!
Sincerely thanks Siguza!
