### ISSUE TITLE
Checkra1n 0.12.2 crashes when running in terminal

### ISSUE THREAD

**Issue by Notalex27** [checkra1n/BugTracker#1928]
**Tell us about your setup:**
1. What iDevice are you using?   Iphone 7
2. On what version of iOS is it?   14.3
3. What version of checkra1n are you using?   0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?   Acer laptop running Ubuntu 20.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Directly to my laptop

**What are the steps to reproduce the issue?**
1. Open terminal
2. Try to run checkra1n in the terminal non cli
3. Press start once the device is connected
...

**What do you expect, and what is happening instead?**
I expected it to ask to put it into recovery mode but instead it just crashes

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No

**Any other info, error logs, screenshots, ...?**
If the device is already in recovery mode it works
If i try to use the gui this dosen't happen
This also happens on my iphone 6 running 12.5 and my iphone 8 running 13.5

**Comment by Siguza** [comment]
Can reproduce.

**Comment by bytenekos** [comment]
Happens on iPhone 7+ and iOS 14.2. Works fine if I use a USB though (so for example odysseyn1x)

edit: I just realized that I’m dumb and checkra1n is version 0.12.1 not 0.12.2

**Comment by TheSpoon334** [comment]
Happens to me as well when using TUI in normal mode... sometimes I also get a message saying "zsh: segmentation fault   sudo checkra1n" but haven't figured out what causes it/how to reproduce. If I start in Recovery it starts attempting the jailbreak as usual (which fails, but that's likely a separate issue). Haven't experienced these crashes with CLI or GUI modes.

**Comment by crystall1nedev** [comment]
@Siguza checkra1n 0.12.2 GUI works if your device is already in Recovery Mode, there’s a tiny problem with Quick Mode (skips the “Get Ready” step) but it works as long as that requirement is met. Tested with iPhone 5s, 12.5.1

**Comment by d3vCr0w** [comment]
I was also having the same problem with 0.12.2 (downloaded from the repository) and solved it by downloading the latest 86_64 binary (0.12.2 as well) from the web page and it worked fine. @Siguza Shouldn't these two be the same? Maybe a difference while compiling?

**Comment by ghost** [comment]
also happens to me, worked fine on arch but since i switched to ubuntu it crashes on the cli

**Comment by erikzmmrmnn** [comment]
Same issue for me. Using the -g switch solved the issue. Using version 0.12.2 that is.

**Comment by noahholl** [comment]
When attempting on Linux Mint it gets the device into DFU mode successfully, but then waits forever at the 'getting ready' step. Ruled out the hardware and cable being at fault because checkn1x works perfectly fine on the exact same machine with the same cable.

**Comment by Siguza** [comment]
Crash should be fixed in 0.12.3.

**Comment by Maruthi2508** [comment]
> Crash should be fixed in 0.12.3.

It is still happening for me. Im on ios 14.4.1 ( iphone 8 ) as soon as i go to options and come back it just gets stuck right there

**Comment by Siguza** [comment]
@Maruthi2508 "getting stuck" sounds like it doesn't crash, so that would be a different issue. If you can reproduce it, please file a new ticket.

**Comment by Maruthi2508** [comment]
> @Maruthi2508 "getting stuck" sounds like it doesn't crash, so that would be a different issue. If you can reproduce it, please file a new ticket.

All right thanks for the response
