### ISSUE TITLE
Still have the same bugs from 0.9.2 (on 0.9.3)

### ISSUE THREAD

**Issue by kobalstone** [checkra1n/BugTracker#298]
**What device + iOS version are you on?**
iPhone 8 Global (iPhone 10,1) iOS 13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. I did the normal "replace old checkra1n app with new checkra1n version" by dragging the new version into applications and ive also done "sudo rm -rf /Applications/checkra1n.app" to make SURE the directory was clean
2. Trying the GUI i get booted but i have the same exact issues i had with the previous update which was disabled sound. disabled haptic feedback. (touch ID works fine though) disabled wifi and i believe thats it
3. Trying CLI i just get bootlooped a few times until it eventually boots into stock
...

**What do you expect, and what is happening instead?**
Im expecting to boot with wifi and haptic feedback and with sound enabled i guess?

Both CLI and GUI both continue as if there was no errors. CLI just holds at "All Done" until i re-enter DFU to try again. GUI just says done and lets me go back to the main menu with no issues.

**Any other info, error logs, screenshots, ...?**
Not right now. GUI and CLI both show success on screen. its the phone with the issue. Im 100% open to trying out private debug/dev builds to help tackle the issue. Ill restore my phone a million times if it helps you guys squash these bugs. @kobalstone on twitter if it makes it easier to message me.

**Comment by kpwn** [comment]
to make sure: everything is still functional when booting stock?

**Comment by kobalstone** [comment]
> to make sure: everything is still functional when booting stock?

yes as far as im aware stock works 100% fine. its only when using checkra1n do i run into issues. im only saying as far as im aware because i personally haven't had any issues in stock no matter the checkra1n version but its possible i may have missed something

**Comment by kpwn** [comment]
We pushed 0.9.3.2, should fix this.

**Comment by kobalstone** [comment]
Update: @kpwn i still have the same issues on 0.9.3.2
Nothing changed for me personally. GUI bootloops and CLI boots with all the previously listed issues

**Comment by kobalstone** [comment]
@kpwn GUI says failed to upload bootstrap.. CLI gives 0 errors but boots with the issues the previous updates had
edit: i can do another fresh restore in a bit and see if it works then

**Comment by kpwn** [comment]
already tried the safe mode switch i guess, and this always happened across all versions released so far, right? it might be a bad kernel patch. can you take a picture of the boot screen with the KPF logs? even without MobileSubstrate, we alter the boot sequence in order to accomodate for it, and suspect that's what is at blame here. i can probably try making a build that skips that (since it's mostly needed for proper MobileSubstrate injection)

**Comment by kobalstone** [comment]
0.9 and 0.9.1 worked perfectly for me.. 0.9.2 is the update that gave me issues and the following updates haven't fixed it for me

edit: just saw your edit and im 100% open to using that build until its fixed.. twitter dms are probably the best way to communicate with me since i have that on all my devices. and ill post screen shots of it all after i shower lol

**Comment by kpwn** [comment]
sent you a dm

**Comment by kobalstone** [comment]
> sent you a dm

i replied

**Comment by nullpixel** [comment]
0.9.5 should have resolved these issues.
