### ISSUE TITLE
Cant install apps while jailbroken 

### ISSUE THREAD

**Issue by zeina99** [checkra1n/BugTracker#504]
**Tell us about your setup:**
1. What iDevice are you using? iphone 7 plus
2. On what version of iOS is it? ios 13.2.2 
3. What version of checkra1n are you using? GUI or CLI? 0.9.5 gui
4. What is your host system (OS version? Hackintosh? VM? etc.)? 
Kvm 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Usb A
**What are the steps to reproduce the issue?**
1. I click on “get”
2. It tells me “payment not completed”
3.
...

**What do you expect, and what is happening instead?**
Cant install apps while jailbroken 
I tried unjailbreaking, and it worked perfectly 

**Does the issue also occur if you enable Safe Mode?**

Yes 
**Any other info, error logs, screenshots, ...?**
I can provide a screenshot but it doesn’t exactly let me do that on mobile

**Comment by zeina99** [comment]
![68B93D31-1E2B-4019-B823-948F4BB2B70A](https://user-images.githubusercontent.com/51930164/69483387-2504f880-0e40-11ea-8286-0099271ec194.png)
Here is a screenshot

**Comment by iCrazeiOS** [comment]
i have it too. however, i found a fix! open settings, and disable TouchID/FaceID for the appstore

**Comment by nullpixel** [comment]
Can you reproduce this issue on 0.9.6?

**Comment by iCrazeiOS** [comment]
I'll try it now

**Comment by iCrazeiOS** [comment]
Just tested. The issue seems to have been fixed!

**Comment by yur1xpp** [comment]
@nullpixel this issue is still happening in 0.9.8.2, even on safe mode.

![FF130CF2-338D-4F26-975F-1632E2EF92D7](https://user-images.githubusercontent.com/34767893/76686844-9bc93a00-6659-11ea-923a-a6d4a2a88d8a.jpeg)
