### ISSUE TITLE
Bootstrap error!

### ISSUE THREAD

**Issue by NoTHyPerz** [checkra1n/BugTracker#520]
![985E1D43-3D00-4B1C-9F67-6B19DF46D3AF](https://user-images.githubusercontent.com/53899382/69640187-f4ad9c00-1083-11ea-9fc7-6552e671007a.png)
How to solve it ?? Pls help me

**Comment by NoTHyPerz** [comment]
My device : IPHONE SE
iOS version : 12.4.1
Checkra1n tool version : 0.9.5 beta

**Comment by boierito** [comment]
Delete the OTA firmware from your iDevice

**Comment by NoTHyPerz** [comment]
I deleted it from the settings and also installed beta tvOS profile to block OTA but I didn’t work.

**Comment by boierito** [comment]
you need to reboot to stock

**Comment by NoTHyPerz** [comment]
> you need to reboot to stock

Do you mean factory reset?

**Comment by boierito** [comment]
No sir, only a reboot

**Comment by NoTHyPerz** [comment]
> No sir, only a reboot

Things I did : 
• Deleted OTA from settings
• Installed tvOS profile
• Rebooted the phone then jailbreaked again but still didn’t work

**Comment by boierito** [comment]
Did you try with safe mode?

**Comment by NoTHyPerz** [comment]
What is safe mode ?

**Comment by NoTHyPerz** [comment]
I updated to iOS 13.2.3 still got the same error. Please help

**Comment by sbingner** [comment]
This was resolved in v0.9.7

**Comment by Ralph-007** [comment]
Its not fixed. I’ve been getting the same issue. I’m on iOS 13.3.

**Comment by Ralph-007** [comment]
![AA75A693-EF95-4B59-9AD2-D0DFC4DF172C](https://user-images.githubusercontent.com/57588773/73013299-e43c4800-3dcc-11ea-8f28-855c6b6b03e8.png)
