### ISSUE TITLE
Cydia Not lunching

### ISSUE THREAD

**Issue by HoSpeLL** [checkra1n/BugTracker#79]
**What device + iOS version are you on?**
iPhone 7 Plus - 13.2.2

**What are the steps to reproduce the issue?**
1. Install checkrain
2. Install Cydia
3. Start Cydia
4. Cydia crashes and closes after launching

**What do you expect, and what is happening instead?**
I expected Cydia to start normally, but instead it crashed.

**Any other info, error logs, screenshots, ...?**
I am thankful for the release of checkrain. I hope that I can somehow contribute to make it even more stable.

**Comment by GithubDev1234** [comment]
I have the same problem, 7 plus ver 13.2

**Comment by HoSpeLL** [comment]
I fixed the problem. Everyone who has the problem can do the following (make sure you have backup of your data):
1. Clean restore your device
2. Jailbreak with Checkrain
3. Install Cydia
4. Install "Cydia Substrate" and "Substrate Safe Mode" from Cydia
5. Restore device from backup in order to get your data back.

That is how I fixed the crashing. I believe there were some leftovers from previous jailbreak (unc0ver) that caused the problem.

**Comment by Shadowedstalker** [comment]
> 
> 
> I fixed the problem. Everyone who has the problem can do the following (make sure you have backup of your data):
> 
>     1. Clean restore your device
> 
>     2. Jailbreak with Checkrain
> 
>     3. Install Cydia
> 
>     4. Install "Cydia Substrate" and "Substrate Safe Mode" from Cydia
> 
>     5. Restore device from backup in order to get your data back.
> 
> 
> That is how I fixed the crashing. I believe there were some leftovers from previous jailbreak (unc0ver) that caused the problem.

thank you for the attempted solution, however it doesn't work, Cydia still crashes.
